### ISSUE TITLE
Medium Armor Master

### ISSUE THREAD

**Issue by Quasxen** [txm3278/midi-item-showcase-community#20]
Foundry v12.331
DnD 5e v3.3.1

I dragged and dropped the Medium Armor Master feat onto a character and it made his AC value blank. I open the Effects that are setup and I see it's using a deprecated Attribute Key
![deprecated and blank](https://github.com/user-attachments/assets/5a397362-e359-472c-a490-3ed75597d6b1)

I tried switching the Attribute Key to system.attributes.ac.formula, but that makes the AC come out to be 0
![valid and 0](https://github.com/user-attachments/assets/bba57177-3530-4ff8-9b2f-9eccf7255cf7)

On another note, the pre-made effect doesn't include the negation of the disadvantage on Stealth. At this time, I can move forward with the effect deleted and just update the item values instead

**Comment by txm3278** [comment]
Should be fixed in latest, let me know if there are any other issues
